# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo tauri build
